DROP TRIGGER IF EXISTS trg_update_total_insert ON BOOKING_ITEM;
DROP TRIGGER IF EXISTS trg_update_total_update ON BOOKING_ITEM;
DROP TRIGGER IF EXISTS trg_update_total_delete ON BOOKING_ITEM;

DROP TRIGGER IF EXISTS trg_decrease_availability ON BOOKING_ITEM;

DROP TRIGGER IF EXISTS trg_restore_availability ON BOOKING;

DROP FUNCTION IF EXISTS update_total_price() CASCADE;
DROP FUNCTION IF EXISTS decrease_room_availability() CASCADE;
DROP FUNCTION IF EXISTS restore_room_availability() CASCADE;

DROP MATERIALIZED VIEW IF EXISTS daily_booking_statistics CASCADE;

DROP VIEW IF EXISTS top_rated_rooms CASCADE;
DROP VIEW IF EXISTS room_statistics CASCADE;
DROP VIEW IF EXISTS guest_booking_statistics CASCADE;

DROP INDEX IF EXISTS idx_guest_email;
DROP INDEX IF EXISTS idx_booking_status;
DROP INDEX IF EXISTS idx_booking_date;
DROP INDEX IF EXISTS idx_booking_item_booking;
DROP INDEX IF EXISTS idx_rates_room;

DROP TABLE IF EXISTS RATES CASCADE;
DROP TABLE IF EXISTS BOOKING_ITEM CASCADE;
DROP TABLE IF EXISTS BOOKING CASCADE;
DROP TABLE IF EXISTS ROOM CASCADE;
DROP TABLE IF EXISTS GUEST CASCADE;